server:
  port: 8080

logging:
  level:
    learning: trace

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/graduated_design?serverTimezone=UTC&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      username: root
    type: com.alibaba.druid.pool.DruidDataSource
  #模板引擎
  freemarker:
    #关闭缓存
    cache: false
    request-context-attribute: request
    #模板加载的位置
    template-loader-path: classpath:/templates
    suffix: .ftl
    settings:
      template_update_delay: 0


# mybatis plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.mapper
  # 如果是放在resource目录 classpath:/mapper/*Mapper.mapper
  mapper-locations: classpath:/mapper/*Mapper.mapper
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fzs.auto_design.entity
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    # refresh-mapper: true
    # 数据库大写下划线转换
    # capital-mode: true
    # Sequence序列接口实现类配置
#  configuration:
#    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'
